"""
Regenerate data.js from the NewHedge API.

The token is read from the NEWHEDGE_TOKEN environment variable and is NEVER
embedded in the site. In CI it comes from an encrypted GitHub Actions secret.

CI-hardened: if ANY series fails to fetch or comes back empty, the script
exits nonzero and writes nothing, so a bad run can never publish a broken
data.js — the site simply keeps serving the previous snapshot.
"""
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

TOKEN = os.environ.get("NEWHEDGE_TOKEN", "")
if not TOKEN:
    sys.exit("Set NEWHEDGE_TOKEN first (newhedge.io/account/api-settings).")

BASE = "https://newhedge.io/api/v2"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/125.0 Safari/537.36")

# (key, url path) — slugs verified against /api/v2/catalog, 2026-06.
SERIES = [
    ("price",    "price/historical"),
    ("drawdown", "metrics/price-drawdown/price_drawdown_btc"),
    ("mvrv_z",   "metrics/mvrv-z-score/mvrv_z"),
    ("mayer",    "metrics/mayer-multiple/mayer_multiple"),
    ("realized", "metrics/realized-price/realized_price"),
    ("nupl",     "metrics/net-unrealized-profit-loss/net_unrealized_profit_loss"),
    # context series (current-reading facts + chart annotations):
    ("pi_fast",  "metrics/pi-cycle-top-indicator/dma_111_btc"),
    ("pi_slow",  "metrics/pi-cycle-top-indicator/dma_350_btc_2"),
    ("lth_cost", "metrics/long-term-holder-realized-price/realized_price_lth"),
    ("vol_1y",   "metrics/volatility-index/price_1y_volatility"),
    ("cagr_2y",  "metrics/cagr/price_cagr_2y"),
]


def fetch(path):
    url = f"{BASE}/{path}?api_token={TOKEN}"
    req = urllib.request.Request(url, headers={"User-Agent": UA,
                                               "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def to_pairs(raw):
    """Normalize to [[ms, value], ...] ascending, nulls dropped."""
    if isinstance(raw, dict):
        for v in raw.values():
            if isinstance(v, list) and v and isinstance(v[0], (list, tuple)):
                raw = v
                break
    pairs = [[int(p[0]), float(p[1])] for p in raw
             if isinstance(p, (list, tuple)) and len(p) >= 2
             and p[1] is not None]
    pairs.sort(key=lambda p: p[0])
    # de-dup timestamps (keep last)
    out = []
    for p in pairs:
        if out and out[-1][0] == p[0]:
            out[-1] = p
        else:
            out.append(p)
    return out


data = {"generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "newhedge.io API v2", "series": {}}
failures = []
for key, path in SERIES:
    try:
        pairs = to_pairs(fetch(path))
        if not pairs:
            raise ValueError("empty series")
        # round to keep the file lean: price/realized to cents, rest 4dp
        nd = 2 if key in ("price", "realized") else 4
        data["series"][key] = [[p[0], round(p[1], nd)] for p in pairs]
        first = datetime.fromtimestamp(pairs[0][0] / 1000, tz=timezone.utc)
        last = datetime.fromtimestamp(pairs[-1][0] / 1000, tz=timezone.utc)
        print(f"  {key:9s} {len(pairs):6d} pts  {first.date()} .. {last.date()}")
    except Exception as e:
        failures.append(key)
        print(f"  FAIL {key}: {e}")

if failures:
    sys.exit(f"Aborting without writing data.js — failed series: {failures}")

last_price = data["series"]["price"][-1]
last_dt = datetime.fromtimestamp(last_price[0] / 1000, tz=timezone.utc)
print(f"  last BTC close: {last_dt.date()} ${last_price[1]:,.0f}")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data.js")
with open(out_path, "w") as fh:
    fh.write("// Generated by refresh_data.py — NewHedge data snapshot. "
             "Do not edit by hand.\n")
    fh.write("window.NH_DATA = ")
    json.dump(data, fh, separators=(",", ":"))
    fh.write(";\n")
print(f"wrote {out_path} ({os.path.getsize(out_path):,} bytes)")
